 # Statistics
 

numbers that hava been collected in order to provide information about something

# the science of collecting and studying these numbers

In [ ]:
eg-
   1 Human =5.6ft
   2 cocount =200ft
 average / mean =102.8

In [10]:
(5.6+200)/2

102.8

In [11]:
(5.6+200+230)/3

145.20000000000002

# mean

There are three tyes

In [ ]:
1.Arithmetic mean
2.Geometric mean
3.Harmonic mean

# 1. Arithmetic Mean

Same range in value

In [ ]:
Formula:-
          X1+X2+X3.......Xn/2

In [3]:
(92+92+92+92+92)/5

92.0

# 2.Geometric Mean:-

# Different Range in value
    Formula:-
        (x1*x2*x3......xn)/1/n
    

In [5]:
import math 
math.sqrt(5.6*200)

33.46640106136302

In [9]:
import math 
(5.6*200*140)**(1/3)

53.923989995517

# 3. Harmonic Mean

Rate of Change in value


In [ ]:
Formula:-
         n/1/n+1/n+1/nn
    

In [ ]:
eg:-
80km
20km 
32km

In [14]:
2/1/80+1/20
1/1+4/80
1/5/80
2*80/5

32.0

In [ ]:
Restra A   B
Rating 3   4
Revies 80  70

In [15]:
import statistics as s
s.geometric_mean((3,80))

15.491933384829666

In [16]:
import statistics as s
s.geometric_mean((4,70))

16.733200530681515

In [ ]:
a=4
b=6

In [18]:
s.mean((4,6))   #Arithmetic mean

5

In [20]:
s.geometric_mean((4,6))   # geometric mean

4.898979485566356

In [21]:
s.harmonic_mean((4,6))    # harmoinic mean

4.8

# median

The middle number found by ordering all data points and picking out the one
in the middle (or if there are two middle number  taking the mean of those two numbers)

 # Median is center point of data 

# Demo:1
        creating a sample data than sorting into ascending order

In [32]:
x=[1,3,2,5,4,7,8,6,9,]
x.sort()
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# There are two types median 

1.Add term median
2.Even term median

# Odd term median:-
                

# Demo:1.1

 odd median :
        
      formula:  M=(n+1/2)th
    
      Where:
            
        n=total number of values
        
        th=term
        
        

In [31]:
x=[1,3,2,5,4,7,8,6,9,]
x.sort()
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# Demo:1.2:

Even term median:
    
    Formula: median=((n/2)th+((n/2)th)/2
                     
        where:
                     
        n= number of terms
                     
        th=term             


In [35]:
y=[0,1,2,3,4,5,6,7,8,9 ]
len(y)

10

In [48]:
z=[3,4,2,6,7,8,9,1,5,0]
z.sort()
print(z)
print(len(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10


In [56]:
def mymedian(n):
    if type(n)==tuple:
        n=list(n)
        n.sort()
    else:
        n.sort()
    
    print((n[(len(n)//2)-1]+n[((len(n)//2)+1)-1])/2)

In [57]:
mymedian(z)

4.5


# Demo:1.3:
  Even median caculation using statistics module  of python 

In [58]:
z=[1,2,3,4,5,6]  # Even median
s.median(z)

3.5

In [59]:
x=[1,2,3,4,5]   # odd median
s.median(x)

3

# Why median:-
   Median helps us to get the understanding
    of data Disbution 

# Mode:

 help to get hoghest occuring value in the dataset 

In [66]:
m=[2,3,3,4,4,5,6,6,7]


 # The most Frequent number:-
    
    That is the number that occurs the highest number of times.

In [64]:
m=[2,3,3,4,4,5,5,6,6,7,8]
s.mode(m)

3

In [65]:
s.multimode(m)

[3, 4, 5, 6]

 # Quantiles:-
              Quantiles are values that separate the data into Four equal Parts.

In [2]:
import statistics as s

In [3]:
x=[1,2,3,4,5,6,7,8]

In [4]:
s.quantiles(x)

[2.25, 4.5, 6.75]

In [5]:
y=[2,2,3,3.24,6,6.7]
s.quantiles(y)

[2.0, 3.12, 6.175]

In [6]:
y=[2,2,3,3.24,6,6.1,8,8.1]
s.quantiles(y)

[2.25, 4.62, 7.525]

In [10]:
q1,q2,q3=s.quantiles(y)

In [11]:
q1

2.25

In [12]:
q2

4.62

In [13]:
q3

7.525

 # IQR:-(inter quartile Range)
        Formula;-(Q3-Q3)

In [15]:
iqr=abs(q1-q3)
print(iqr)

5.275


In [16]:
iqr=abs(q3-q1)
print(iqr)

5.275


# Trend:-
         

In [17]:
dataset=[-10000,100,200000,300000,2500000]
q1,q2,q3=s.quantiles(dataset)

In [18]:
s.quantiles(dataset)

[-4950.0, 200000.0, 1400000.0]

# There are Two types of Trend:-
        1. MAX_Trend
    
        2.MIN_Trend

# 1.MAX_Trend:-
             Formula:-Max_trend=q3+1.5*iqr

In [19]:
max_trend=q3+1.5*iqr

In [20]:
max_trend

1400007.9125

# 2.MIN_Trend:-
               Formula:- min_trend=q1-1.5*iqr

In [22]:
min_trend=q1-1.5*iqr

In [23]:
min_trend

-4957.9125

In [24]:
filter_dataset=[]
for i in dataset:
    if min_trend<i<max_trend:
        filter_dataset.append(i)
print(filter_dataset)

[100, 200000, 300000]


In [31]:
filter_dataset=[]
for i in dataset:
    if min_trend<i and max_trend>i:
        filter_dataset.append(i)
print(filter_dataset)

[100, 200000, 300000]


# Name of The tolls hold structure data:-
1.Database:-(sql database)

2.HTML Table:-(semi structure data in all)

3.XML:-

4.WML:-

5.EXCEL:-

6.MS Excess:-



#  Unstructure Data :-
                 A Dataset which has no level of it column called Unstructured Data
Tolls:- Numpy (Develop in 2005 for built in c++ Language)

# Numpy Download:
               python.org(numpy) pip install Numpy

In [32]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [33]:
import numpy as np

In [34]:
np.array([1,2,3,4,5,6,7,8])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
print(a)

[1 2 3 4 5 6 7 8]


In [37]:
b=[1,2,3]
print(b)

[1, 2, 3]


In [39]:
c=np.array([1,"deepak",1.4])
print(c)

['1' 'deepak' '1.4']


In [41]:
c=np.array([1,"deepak",1.4])
c

array(['1', 'deepak', '1.4'], dtype='<U32')

In [48]:
e=np.array([1,2.4])
print(e)

[1.  2.4]


In [65]:
f=np.array([1,2,3,"6"],dtype=np.int8)  # convert to int
print(f)


[1 2 3 6]


In [66]:
e=np.array([1,2,"3.4"],dtype=np.float16)    # convert to float

In [67]:
print(e)

[1.  2.  3.4]


In [68]:
bin(10)    # convert to byte 

'0b1010'

In [69]:
max(np.array([1,2,3]))

3

In [72]:
min(np.array([2,5,8]))

2

In [70]:
f=np.array([1,2,3,"5"],dtype=np.float16)  # convert to float
print(f)
g=np.array(f,dtype=np.int16)      # convert to integer
print(g)

[1. 2. 3. 5.]
[1 2 3 5]


In [74]:
h=np.array([3,7,9,8],dtype=np.str_)   # convert to String
print(h)

['3' '7' '9' '8']


# There are Three Types of Array:
1.Scaler:-(mangnitude)

2.Vector:-(mangnitude & direction)

3.Matrix:-

# 1.Scaler:-
          A Value Which has not 0 dimension
    
    

In [77]:
i=np.array(100)   # Scaler array which has no dimension or 0 dimension
print(i)
i

100


array(100)

# 2.Vector:-
            1 Dimensional array of vector 

In [80]:
j=np.array([100])   # 1 Dimensional array of Vector
print(j)
j

[100]


array([100])

# 3.Matrix:-
          2D array called matrix

In [86]:
k=np.array([[2,3],[6,7]])   # 2D array
print(k)
k

[[2 3]
 [6 7]]


array([[2, 3],
       [6, 7]])

In [89]:
l=np.array([[[100]]])     # 3D array
print(l)
l

[[[100]]]


array([[[100]]])

In [96]:
l=np.array([[[0,9],[6,7]],[[8,5],[2,1]]])  # 3D array
print(l)
l
l.ndim

[[[0 9]
  [6 7]]

 [[8 5]
  [2 1]]]


3

# ndim:-
       Number of Dimension

In [98]:
toy=np.array(["video game","computer","turn card"])
toy

array(['video game', 'computer', 'turn card'], dtype='<U10')

In [99]:
marks=np.array([[1,'A',23,60],[2,'B',22,50],[3,'C',34,78]]);
marks

array([['1', 'A', '23', '60'],
       ['2', 'B', '22', '50'],
       ['3', 'C', '34', '78']], dtype='<U11')

 # 3D:-
     image store

In [5]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [2]:
import cv2
print(img)
cv2.imread("C:\Users\DELL\Desktop/cute.jpg")
cv2.imsho('win'img)
cv2.waitkey()
cv2.destroy all windows()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (4153321437.py, line 3)

# Application Array:-
1.0D:-22(mangnitude)

2.1D:-To create list

3.2D:-To store tabular data

4.3D:-3D array used to store image

5.4D:-To store video

In [21]:
demo1=[i for i in range(100)]
print(demo1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [22]:
 import numpy as np

In [23]:
demo2=np.array([i for i in range (100)])
print(demo2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# Array is Faster than list:

In [24]:
import sys
sys.getsizeof(demo1)

920

In [25]:
sys.getsizeof(demo2)

504

In [30]:
np.random.randint(1,10)   # change in value 

3

In [33]:
np.random.randint(1,10,5)

array([5, 8, 3, 7, 6])

In [36]:
np.random.randint(1,10,(3,5))

array([[2, 2, 1, 6, 3],
       [4, 2, 7, 5, 1],
       [8, 8, 1, 7, 4]])

In [39]:
np.random.randint(1,10,(3,3,2))

array([[[2, 4],
        [7, 6],
        [6, 9]],

       [[2, 6],
        [8, 6],
        [3, 4]],

       [[9, 7],
        [7, 2],
        [6, 8]]])

In [44]:
np.random.uniform(1,10,2)    # float value

array([8.77150003, 5.05046738])

In [45]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
np.linspace(0,9.5,20)   # uniformly equil distance data create using linspace between two point start and end head are inclusive

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# flatten

In [56]:
x=np.random.randint(1,10,(3,2))
print(x)

[[6 4]
 [6 1]
 [7 8]]


In [58]:
x.flatten()   # 2D array convert 1D array

array([6, 4, 6, 1, 7, 8])

In [59]:
x.resize((2,3))   # parament change

In [60]:
x

array([[6, 4, 6],
       [1, 7, 8]])

In [64]:
z=np.random.randint(1,5,(3,2))
z

array([[2, 4],
       [3, 3],
       [4, 4]])

In [66]:
z.flatten()


array([2, 4, 3, 3, 4, 4])

In [68]:
z.reshape((2,3))    # not parament change
z

array([[2, 4],
       [3, 3],
       [4, 4]])

In [69]:
z.reshape((2,3),order='F')

array([[2, 4, 3],
       [3, 4, 4]])

In [70]:
z.reshape((2,3),order='c')

array([[2, 4, 3],
       [3, 4, 4]])

In [73]:
array1=np.arange(16)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
array1.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
array1.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [76]:
array1.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [82]:
array1.reshape((-1,2),order='f')


array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [85]:
len((array1.reshape(2,8).flatten()))

16

In [87]:
a=array1.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
a.resize((3,4),refcheck=False)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Broadcasting:-

In [95]:
l1=[1,2,3,4,5]
l2=[4,5,6,7,8]
l1+l2

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

# list broadcasting using fro loop 
Rule:-1

In [96]:
for i, j in zip(l1,l2):   # using loop
    print(i+j)

5
7
9
11
13


In [104]:
empty=[]
for i,j in zip(l1,l2):
    empty.append(i+j)
empty

[5, 7, 9, 11, 13]

In [107]:
array1=np.array([1,2,3,4,5])
array2=np.array([4,5,6,7,8])
array1+array2

array([ 5,  7,  9, 11, 13])

# Rule2:-

In [115]:
empty2=[i+j for i,j in zip(l1,l2)]
empty2

[5, 7, 9, 11, 13]

In [121]:
np.concatenate((array1,array2))

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [122]:
array1*array2

array([ 4, 10, 18, 28, 40])

In [123]:
array1/array2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

In [124]:
array1//array2

array([0, 0, 0, 0, 0], dtype=int32)

In [125]:
array1-array2

array([-3, -3, -3, -3, -3])

In [126]:
np.round(array1/array2.decimals=2)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3638629262.py, line 1)